name: purplepong
summary: A small game I made in my free time (with a tutorial cause I'm not great at programming)
description: |
  It's pong but it's purple :D,
  Left player moves with W and S,
  Right player moves with the beloved up and down arrow keys,
version: test  
base: core22  
confinement: strict

parts:
  purplepong:
    plugin: python
    python-packages:
      - pygame
    python-version: python3
    source: https://github.com/lem0nmel0n/purple-pong.git  
    stage-packages:
    - python3-usb
    
apps:
  purplepong:
    command: bin/purplepong  

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x    

