name: purplepong 
base: core22
version: '1' 
summary: A small game of pong. 
description: |
  it's pong but it's purple :D,
  left player moves with W and S,
  right player moves with the up and down arrow keys,

grade: stable
confinement: strict
parts:
    purplepong:
      plugin: python
      python-packages:
        - pygame
    
      source-type: git  
      source: https://github.com/lem0nmel0n/purple-pong.git
    
apps:
  purplepong:
    command: bin/purplepong     


architectures:
  - build-on: s390x
  - build-on: ppc64el
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64 
